version: '3'

services:
  mongodb:
    image: mongo:latest
    networks:
      - bridgeTP6
    volumes:
      - ./db:/data/db
  web:
    build: .
    container_name: tp6-flask
    ports:
      - "5000:5000"
    networks:
      - bridgeTP6
    volumes:
      - ./text_file.txt:/app/text_file.txt
    depends_on:
      - mongodb
networks:
  bridgeTP6:
    driver: bridge
